services:
  recordtree-web:
    build:
      context: .
    image: recordtree-downloader-sqlite-web:dev
    container_name: recordtree-web
    ports:
      - "8000:8000"
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./env:/app/env
      - ./downloads:/app/downloads
      - ./logs:/app/logs
      - ./files:/app/files
      - ./env/megacmd-home:/root
    restart: unless-stopped
